model:
  name: "vngrs-ai/Kumru-2B-Base"
  max_length: 512

lora:
  r: 8
  alpha: 16
  dropout: 0.05

training:
  epochs: 10
  batch_size: 1
  learning_rate: 2e-4
  gradient_accumulation_steps: 4
  output_dir: "./training-checkpoints"

data:
  file: "sampledataset.jsonl"

final:
  adapter_path= "./kumru-2B-finetuned"
